import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'Bar.dart';
import 'Search.dart';

class ComplaintsAnalysis extends StatefulWidget {
  @override
  _ComplaintsAnalysisState createState() => _ComplaintsAnalysisState(
      Email: Email,
      Password: Password,
      username: username,
      mobile: mobile,
      Gender: Gender,
      dob: dob,
      id: id,
      Adress: Adress,
      nationalid: nationalid);

  var Email = "";
  var Password = "";
  var username = "";
  var mobile = "";
  var Gender = "";
  var dob = "";
  var id = "";
  var Adress = "";
  var nationalid = "";

  ComplaintsAnalysis({
    required this.Email,
    required this.Password,
    required this.username,
    required this.mobile,
    required this.Gender,
    required this.dob,
    required this.id,
    required this.Adress,
    required this.nationalid,
  });
}

class _ComplaintsAnalysisState extends State<ComplaintsAnalysis> {
  var Email = "";
  var Password = "";
  var username = "";
  var mobile = "";
  var Gender = "";
  var dob = "";
  var id = "";
  var Adress = "";
  var nationalid = "";

  _ComplaintsAnalysisState({
    required this.Email,
    required this.Password,
    required this.username,
    required this.mobile,
    required this.Gender,
    required this.dob,
    required this.id,
    required this.Adress,
    required this.nationalid,
  });

  List<dynamic> feedbackList = [];

  @override
  void initState() {
    super.initState();
    fetchFeedback();
  }

  // Fetch the feedback from your API endpoint
  Future<void> fetchFeedback() async {
    String url = 'https://inconspicuous-pairs.000webhostapp.com/feddback.php';
    var response = await http.get(Uri.parse(url));
    if (response.statusCode == 200) {
      setState(() {
        feedbackList = json.decode(response.body);
      });
    } else {
      throw Exception('Failed to load feedback');
    }
  }

  // Define a function to preprocess the feedback
  String preprocessFeedback(String feedback) {
    // change to lower case
    feedback = feedback.toLowerCase();
    // Remove any special characters or punctuation
    feedback = feedback.replaceAll(RegExp(r'[^\w\s]'), '');
    return feedback;
  }

// Split into sentences while preserving Arabic text
  List<String> splitSentences(String text) {
    RegExp re = RegExp(r'(?<=[.!?])\s+(?=[الأ-يA-Z])');
    List<String> sentences = re.allMatches(text).map((m) => m.input.substring(m.start, m.end)).toList();

    // Rejoin any Arabic sentences that were incorrectly split
    for (int i = 0; i < sentences.length - 1; i++) {
      if (sentences[i+1].startsWith('ال ') || sentences[i+1].startsWith('ذو ')) {
        sentences[i] += ' ' + sentences[i+1];
        sentences.removeAt(i+1);
        i--;
      }
    }
    return sentences;
  }

  // Define a function to analyze the sentiment of the feedback
  String analyzeSentiment(String feedback) {
    // Preprocess the feedback
    feedback = preprocessFeedback(feedback);
    // Perform sentiment analysis (positive, negative, or neutral)
    // You can use any NLP library to perform this analysis, such as NLTK or spaCy
    // Here, we'll use a simple rule-based approach with a list of positive and negative keywords
    List<String> positiveKeywords = [
      'accessible',
      'accommodating',
      'accountable',
      'accurate',
      'achievable',
      'adaptive',
      'affordable',
      'agile',
      'alert',
      'ambitious',
      'amenable',
      'analytical',
      'appropriate',
      'assured',
      'attentive',
      'authentic',
      'authoritative',
      'availability',
      'balanced',
      'beneficial',
      'best',
      'better',
      'bolstered',
      'brave',
      'bright',
      'broad-minded',
      'businesslike',
      'canny',
      'capable',
      'captivating',
      'caring',
      'casual',
      'celebrated',
      'certain',
      'charismatic',
      'charitable',
      'charming',
      'cheerful',
      'choice',
      'chosen',
      'civil',
      'classic',
      'clear',
      'clever',
      'cogent',
      'collaborative',
      'comfortable',
      'committed',
      'communicative',
      'compassionate',
      'competitive',
      'complementary',
      'complete',
      'composed',
      'comprehensive',
      'confident',
      'congenial',
      'consistent',
      'constructive',
      'consumer-friendly',
      'contemporary',
      'convenient',
      'cool',
      'cooperative',
      'coordinated',
      'cordial',
      'correct',
      'courageous',
      'creative',
      'credible',
      'cultivated',
      'culturally sensitive',
      'curious',
      'customer-centric',
      'customer-focused',
      'customer-oriented',
      'cutting-edge',
      'daring',
      'dazzling',
      'decent',
      'decisive',
      'dedicated',
      'deep',
      'definitive',
      'delightful',
      'dependable',
      'desirable',
      'detailed',
      'determined',
      'devoted',
      'diagnostic',
      'diffusive',
      'diligent',
      'direct',
      'discerning',
      'discreet',
      'discriminating',
      'distinctive',
      'distinguished',
      'diverse',
      'dynamic',
      'earnest',
      'easy',
      'easygoing',
      'economical',
      'educated',
      'effective',
      'efficient',
      'elated',
      'elegant',
      'empathetic',
      'empowered',
      'encouraging',
      'enduring',
      'energetic',
      'engaging',
      'enhanced',
      'enjoyable',
      'enriching',
      'enthusiastic',
      'entrepreneurial',
      'equitable',
      'essential',
      'established',
      'ethical',
      'eventful',
      'ever-ready',
      'exceptional',
      'exciting',
      'exemplary',
      'experienced',
      'expert',
      'exploratory',
      'expressive',
      'exquisite',
      'extraordinary',
      'exuberant',
      'facilitative',
      'fair',
      'faithful',
      'familiar',
      'famous',
      'fantastic',
      'fascinating',
      'fast',
      'favorable',
      'fearless',
      'feisty',
      'fierce',
      'fine',
      'firm',
      'flexible',
      'flourishing',
      'fluent',
      'focused',
      'forceful',
      'foremost',
      'formidable',
      'fortified',
      'fortuitous',
      'forward-looking',
      'fostering',
      'foundational',
      'free',
      'fresh',
      'friendly',
      'fulfilled',
      'fulfilling',
      'full',
      'funny',
      'futuristic',
      'gallant',
      'generative',
      'generous',
      'genuine',
      'gifted',
      'giving',
      'glad',
      'glorious',
      'goal-oriented',
      'golden',
      'good',
      'gorgeous',
      'graceful',
      'gracious',
      'grand',
      'great',
      'groundbreaking',
      'growing',
      'guiding',
      'handy',
      'happy',
      'hardworking',
      'harmonious',
      'hassle-free',
      'headstrong',
      'healthy',
      'heartfelt',
      'helpful',
      'heroic',
      'high-quality',
      'highly regarded',
      'honest',
      'honorable',
      'hopeful',
      'humble',
      'humorous',
      'ideal',
      'imaginative',
      'impartial',
      'impeccable',
      'impressive',
      'improving',
      'incisive',
      'inclusive',
      'incomparable',
      'incredible',
      'independent',
      'indispensable',
      'innovative',
      'insightful',
      'inspiring',
      'integrated',
      'intelligent',
      'intense',
      'interactive',
      'interested',
      'interesting',
      'intuitive',
      'invaluable',
      'invigorating',
      'inviting',
      'irresistible',
      'jaunty',
      'jolly',
      'jovial',
      'joyful',
      'joyous',
      'judicious',
      'just',
      'keen',
      'kind',
      'knowledgeable',
      'laudable',
      'leading',
      'learned',
      'legitimate',
      'lenient',
      'liberal',
      'light-hearted',
      'likable',
      'limitless',
      'lively',
      'logical',
      'long-lasting',
      'lovable',
      'lovely',
      'loyal',
      'lucid',
      'lucky',
      'luxurious',
      'magical',
      'magnetic',
      'magnificent',
      'majestic',
      'marvelous',
      'masterful',
      'meaningful',
      'meditative',
      'memorable',
      'merry',
      'meticulous',
      'mindful',
      'modern',
      'well',
      'modest',
      'motivated',
      'motivating',
      'multi-faceted',
      'multidimensional',
      'navigable',
      'neat',
      'necessary',
      'nice',
      'nimble',
      'noble',
      'nonviolent',
      'notable',
      'noticeable',
      'nurturing',
      'objective',
      'observant',
      'open',
      'open-minded',
      'optimistic',
      'orderly',
      'organized',
      'original',
      'outgoing',
      'outstanding',
      'overachieving',
      'passionate',
      'patient',
      'peaceful',
      'perfect',
      'perceptive',
      'persistent',
      'persuasive',
      'phenomenal',
      'pioneering',
      'playful',
      'pleasant',
      'pleased',
      'pleasing',
      'plentiful',
      'plucky',
      'poised',
      'polished',
      'popular',
      'positive',
      'potent',
      'practical',
      'pragmatic',
      'precise',
      'preferred',
      'premier',
      'prepared',
      'present',
      'prestigious',
      'pretty',
      'prevailing',
      'productive',
      'professional',
      'proficient',
      'promising',
      'prompt',
      'proper',
      'prospective',
      'prosperous',
      'protective',
      'proud',
      'proven',
      'prudent',
      'punctual',
      'pure',
      'purposeful',
      'qualified',
      'quaint',
      'quick',
      'quiet',
      'radiant',
      'rational',
      'ready',
      'realistic',
      'reasonable',
      'reassuring',
      'receptive',
      'recognized',
      'reliable',
      'remarkable',
      'remunerative',
      'renewed',
      'renowned',
      'reputable',
      'resilient',
      'resourceful',
      'respected',
      'responsible',
      'responsive',
      'restorative',
      'revered',
      'rewarding',
      'rich',
      'right',
      'robust',
      'romantic',
      'safe',
      'satisfactory',
      'satisfied',
      'savvy',
      'scholarly',
      'scrupulous',
      'seasoned',
      'secure',
      'self-assured',
      'self-confident',
      'self-motivated',
      'sensible',
      'sensitive',
      'sensuous',
      'serious',
      'service-oriented',
      'settled',
      'sharing',
      'sharp',
      'shining',
      'shrewd',
      'significant',
      'silent',
      'silly',
      'sincere',
      'skillful',
      'smart', 'error-free', 'no-delay', 'no-glitch', 'glitch-free',
      "أنا سعيد جدًا بخدمات البنك الإلكتروني، فهي توفر الوقت والجهد وتجعل الحياة أسهل.",
      "التطبيق سريع وسهل الاستخدام، ويوفر العديد من الخيارات الرائعة لإدارة حسابي المصرفي.",
      "لقد تمكنت من إجراء جميع المعاملات المصرفية اللازمة عن بعد باستخدام البنك الإلكتروني، ولم أواجه أي مشكلة.",
      "أحببت كيف يسهل التطبيق إجراء التحويلات المصرفية ودفع الفواتير، كما أنه يوفر معلومات دقيقة عن رصيد الحساب والمعاملات السابقة.",
      "لقد كانت تجربتي الشخصية مع البنك الإلكتروني ممتازة، وأوصي به بشدة لأي شخص يبحث عن طريقة سهلة وآمنة لإدارة حسابه المصرفي.",
      'سعيد',
      'ممتاز',
      'رائع',
      'سهل',
      'فعال',
      'مريح',
      'مفيد',
      'موثوق',
      'متاح',
      'مرن',
      'مبتكر',
      'مبسط',
      'جيد',
      'متطور',
      'آمن',
      'متقدم',
      'منظم',
      'متكامل',
      'مريح',
      'سريع',
      'سلس',
      'استثنائي',
      'متعدد الخيارات',
      'مستخدم ودود',
      'عملي',
      'متفوق',
      'ذكي',
      'موفر للوقت',
      'متوافق',
      'مثالي',
      'فاعل',
      'مبتكر',
      'آمن',
      'عالي الأداء',
      'منسق',
      'شامل',
      'مريح',
      'متناغم',
      'متاح على مدار الساعة',
      'ذكي',
      'مبتكر',
      'سهل الاستخدام',
      'متكامل',
      'سلس',
      'فاعل',
      'موفر للوقت',
      'رائع',
      'متطور',
      'أنيق',
      'مناسب',
      'فعال جداً',
      'مفيد جداً',
      'عملي جداً',
      'متقدم',
      'منظم جداً',
      'متكامل جداً',
      'مريح جداً',
      'سريع جداً',
      'سهل جداً',
      'فعال جداً',
      'مريح جداً في الاستخدام',
      'منظم تماماً',
      'متكامل بشكل كامل',
      'سهل الفهم',
      'مناسب جداً',
      'مناسب تماماً',
      'متطور جداً',
      'فعالية عالية',
      'تصميم أنيق',
      'جميل',
      'مفيد للغاية',
      'أداء ممتاز',
      'جيد جداً',
      'سهل التنزيل',
      'مناسب تماماً للمستخدم',
      'جيد في الاستخدام',
      'متاح على مدار الساعة',
      'ملائم',
      'متكامل بشكل كامل',
      'متوافق جيداً',
      'منظم بشكل كامل',
      'مريح جداً في الاستخدام',
      'فعال جداً',
      'متطور بشكل كامل',
      'مفيد جداً جداً',
      'جيد في الأداء',
      'رائع جداً',
      'متاح في الاستخدام',
      'سهل الفهم جداً',
      'مناسب تماماً للمستخدم',
      'متوافق جيداً',
      'منظم بشكل كامل',
      'متكامل بشكل كامل',
      'مميز',
      'مرضي',
      'معقول',
      'مركزي',
      'تفصيلي',
      'متكامل جداً',
      'سهل الفهم جداً',
      'فعال جداً',
      'متاح على مدار الساعة',
      'سلس جداً',
      'دقيق',
      'متوافق تماماً',
      'مرن جداً',
      'مبتكر جداً',
      'مفيد للغاية',
      'منظم بشكل جيد',
      'سهل التنقل',
      'مناسب للمستخدمين',
      'مناسب لجميع الأعمار',
      'أمن جداً',
      'مناسب للأعمال المصرفية',
      'مجاني',
      'متوافق مع جميع الأجهزة',
      'منظم تماماً',
      'مثالي جداً',
      'فعال جداً في التحويلات المصرفية',
      'مريح جداً في استخدام الخدمات المصرفية',
      'متاح في جميع الأوقات',
      'متوافق مع المعايير الدولية',
      'منظم بشكل جيد جداً',
      'متوافق مع جميع أنواع الأجهزة الذكية',
      'ملائم للجميع',
      'موفر للوقت جداً',
      'فعال في إدارة المدفوعات الإلكترونية',
      'مناسب للشركات',
      'مناسب للمؤسسات المالية',
      'آمن جداً في الاستخدام',
      'متوافق مع الأنظمة الأمنية العالمية',
      'متكامل بشكل كامل مع الخدمات المصرفية',
      'سهل الفهم والاستخدام',
      'مناسب للأفراد والشركات',
      'مريح جداً في الاستخدام',
      'فاعل جداً في إدارة الحسابات المصرفية',
      'مناسب تماماً للأعمال المصرفية',
      'متوافق مع الأنظمة المصرفية الدولية',
      'فعال جداً في إدارة المعاملات المالية',
      'مناسب للأفراد والشركات على حد سواء',
      'مرن وسهل الاستخدام',
      'موفر للوقت والجهد',
      'مناسب للأعمال المصرفية الصغيرة',
      'سهل التنقل والاستخدام',
      'مناسب تماماً للمستخدمين الجدد',
      'فعال في تحويل الأموال الدولية',
      'مريح جداً في الاستخدام اليومي',
      'متوافق مع المعايير العالمية للأمن',
      'منظم بشكل جيد لإدارة الحسابات المصرفية',
      'متطور جداً في تقديم الخدمات المصرفية الرقمية',
      'مناسب للأعمال المصرفية الكبيرة',
      'مناسب للأفراد والشركات والمؤسسات المالية',
      'فعال في توفير الخدمات المصرفية عبر الإنترنت',
      'سهل الفهم والاستخدام حتى للمبتدئين',
      'مريح جداً في إدارة الحسابات والمعاملات المصرفية',
      'مناسب جداً للتجار وأصحاب الأعمال',
      'متوافق مع الأنظمة المصرفية الوطنية',
      'متكامل بشكل كامل مع خدمات الدفع الإلكتروني',
      'فاعل في توفير الخدمات المصرفية عن بعد',
      'مريح جداً في الاستخدام والتحكم بالحسابات المصرفية',
      'متوافق مع جميع الأنظمة البنكية العالمية',
      'فعال في توفير الخدمات المصرفية الشخصية',
      'مناسب للأعمال المصرفية الصغيرة والمتوسطة',
      'مناسب للأفراد والشركات والمؤسسات المالية',
      'فعال جداً في توفير الخدمات المصرفية عبر الهاتف المحمول',
      'مريح جداً في الاستخدام والتحكم بالحسابات المصرفية',
      'متوافق مع الأنظمة المصرفية الدولية والوطنية',
      'مناسب للأعمال المصرفية الكبرى والمتوسطة',
      'فعالية عالية في توفير الخدمات المصرفية',
      'سهولة في التحكم بالحسابات المصرفية والمعاملات المالية',
      'مناسب تماماً للأفراد والشركات والمؤسسات المالية',
      'فعال في توفير الخدمات المصرفية عبر الإنترنت والهاتف المحمول',
      'مريح جداً في الاستخدام والتحكم بالحسابات المصرفية',
      'متوافق مع جميع أنظمة الدفع الإلكتروني',
      'مناسب للأعمال المصرفية الصغيرة والمتوسطة',
      'فعال جداً في توفير الخدمات المصرفية الشخصية',
      "سهل الفهم والاستخدام حتى للمبتدئين",
      'سهل',
      'الفهم',
      'توفير',
      'فعال',
      "جداً",
      "متوافق",
      "مناسب"
    ];
    List<String> negativeKeywords = [
      'abysmal',
      'adverse',
      'is not ',
      'not helpful',
      'this app is not helpful'
          'afraid',
      'aggravating',
      'aggressive',
      'agonizing',
      'aimless',
      'alarmed',
      'alienated',
      'allergic',
      'ambiguous',
      'amiss',
      'anarchic',
      'angry',
      'anguished',
      'annoyed',
      'anxious',
      'apathetic',
      'appalling',
      'arrogant',
      'ashamed',
      'atrocious',
      'attacked',
      'awful',
      'awkward',
      'bad',
      'banal',
      'barbaric',
      'barren',
      'belligerent',
      'bemoaning',
      'beneath',
      'bereaved',
      'bewildered',
      'bizarre',
      'blah',
      'bleak',
      'blinding',
      'blockheaded',
      'bloody',
      'blundering',
      'blurry',
      'boastful',
      'bogus',
      'bothersome',
      'bowed',
      'boxed-in',
      'boyish',
      'brash',
      'bratty',
      'brazen',
      'breakable',
      'broken',
      'bruised',
      'brutal',
      'buggy',
      'bullheaded',
      'burdensome',
      'burned-out',
      'busy',
      'cagey',
      'callous',
      'can’t',
      'careless',
      'chaotic',
      'cheap',
      'cheated',
      'cheesy',
      'chilly',
      'choked',
      'clammy',
      'clueless',
      'clumsy',
      'coarse',
      'cold',
      'colorless',
      'commonplace',
      'complicated',
      'compromised',
      'conceited',
      'concerned',
      'confused',
      'constricted',
      'contemptuous',
      'contrary',
      'corroded',
      'corrupted',
      'costly',
      'crazy',
      'creepy',
      'criminal',
      'critical',
      'crude',
      'cruel',
      'crummy',
      'crushed',
      'crying',
      'cryptic',
      'cursed',
      'cut-off',
      'cynical',
      'damaged',
      'damaging',
      'dangerous',
      'dazed',
      'dead',
      'dead-end',
      'deaf',
      'debased',
      'deceitful',
      'deceived',
      'deceptive',
      'defeated',
      'defective',
      'defenseless',
      'defiant',
      'deficient',
      'degraded',
      'dejected',
      'delicate',
      'deluded',
      'demanding',
      'demented',
      'demoralized',
      'denied',
      'dependent',
      'depleted',
      'depraved',
      'depressed',
      'deprived',
      'deranged',
      'deserted',
      'desolate',
      'despairing',
      'desperate',
      'despicable',
      'destroyed',
      'destructive',
      'detached',
      'detrimental',
      'devastated',
      'devastating',
      'deviant',
      'devious',
      'difficult',
      'dim',
      'dirty',
      'disabled',
      'disadvantaged',
      'disappointed',
      'disappointing',
      'disapproved',
      'disastrous',
      'disconnected',
      'discontented',
      'discouraged',
      'discouraging',
      'discredited',
      'disdainful',
      'disgraced',
      'disgusted',
      'disheartened',
      'dishonest',
      'disillusioned',
      'disinclined',
      'disinterested',
      'disjointed',
      'dislike',
      'disliked',
      'dismal',
      'dismayed',
      'disorganized',
      'disoriented',
      'displeased',
      'disposable',
      'disrespected',
      'disruptive',
      'dissatisfied',
      'dissipated',
      'dissolute',
      'distant',
      'distasteful',
      'distorted',
      'distraught',
      'distressed',
      'disturbed',
      'divisive',
      'dizzy',
      'doomed',
      'doubtful',
      'dozy',
      'drab',
      'drained',
      'dreadful',
      'dreary',
      'drenched',
      'dull',
      'dumb',
      'dumped',
      'duped',
      'dying',
      'earnest',
      'edgy',
      'egocentric',
      'egotistical',
      'elusive',
      'embarrassed',
      'embattled',
      'empty',
      'enervated',
      'enfeebled',
      'engulfed',
      'enraged',
      'enraptured',
      'enslaved',
      'enthralled',
      'entrenched',
      'envious',
      'erratic',
      'erroneous',
      'estranged',
      'evaded',
      'evil',
      'excluded',
      'exhausted',
      'exiled',
      'exploited',
      'exposed',
      'extravagant',
      'extremist',
      'failed',
      'fake',
      'fanciful',
      'fanatical',
      'fatal',
      'fatigued',
      'faulty',
      'fearful',
      'feeble',
      'feigned',
      'fickle',
      'fierce',
      'filthy',
      'fleeting',
      'flimsy',
      'flustered',
      'foolish',
      'forced',
      'forgetful',
      'forgotten',
      'forsaken',
      'fractured',
      'fragile',
      'fragmented',
      'frantic',
      'fraudulent',
      'frazzled',
      'freaked-out',
      'frightened',
      'frigid',
      'frustrated',
      'fuming',
      'funereal',
      'furious',
      'futile',
      'galled',
      'gaunt',
      'ghastly',
      'ghostly',
      'gloomy',
      'glum',
      'gory',
      'grating',
      'gray',
      'greedy',
      'grief-stricken',
      'grieving',
      'grim',
      'grimy',
      'grotesque',
      'grouchy',
      'grubby',
      'gruesome',
      'grumpy',
      'guilty',
      'gullible',
      'hapless',
      'hard',
      'hard-hearted',
      'harmed',
      'harried',
      'harrowed',
      'hateful',
      'haunted',
      'heartbroken',
      'heavy',
      'hedonistic',
      'helpless',
      'hesitant',
      'hideous',
      'high-and-mighty',
      'hollow',
      'hopeless',
      'horrible',
      'horrific',
      'hostile',
      'hounded',
      'humiliated',
      'hungry',
      'hurt',
      'hysterical',
      'idiotic',
      'ignorant',
      'ignored',
      'ill',
      'ill-advised',
      'ill-fated',
      'ill-natured',
      'ill-treated',
      'ill-tempered',
      'imbalanced',
      'immaterial',
      'immoderate',
      'impaired',
      'impossible',
      'impractical',
      'imprecise',
      'imprisoned',
      'impure',
      'inaccessible',
      'inaccurate',
      'inadequate',
      'inane',
      'inappropriate',
      'inarticulate',
      'incapable',
      'incensed',
      'incessant',
      'inactive',
      'inadequate',
      'inattentive',
      'incensed',
      'incapable',
      'incessant',
      'incomplete',
      'incomprehensible',
      'incongruous',
      'inconsequential',
      'inconsiderate',
      'inconsistent',
      'inconvenient',
      'incorrect',
      'incorrigible',
      'incredulous',
      'indebted',
      'indecent',
      'indecisive',
      'indifferent',
      'indignant',
      'indiscreet',
      'indiscriminate',
      'indolent',
      'indulgent',
      'ineffective',
      'inefficient',
      'inert',
      'inescapable',
      'inevitable',
      'inexcusable',
      'inexperienced',
      'inferior',
      'infuriated',
      'injured',
      'injudicious',
      'insecure',
      'insensitive',
      'insidious',
      'insignificant',
      'insincere',
      'insipid',
      'insistent',
      'insolent',
      'insomnia',
      'insulted',
      'insupportable',
      'insurmountable',
      'intense',
      'interfering',
      'interminable',
      'interrupted',
      'intimidated',
      'intolerable',
      'intricate',
      'intrusive',
      'inundated',
      'inured',
      'invalid',
      'invasive',
      'invincible',
      'irate',
      'irksome',
      'irrational',
      'irresponsible',
      'irreverent',
      'irritated',
      'isolated',
      'jaded',
      'jealous',
      'jittery',
      'jumpy',
      'juvenile',
      'kaput',
      'killed',
      'knocked-down',
      'lacking',
      'lagging',
      'lame',
      'languid',
      'languished',
      'laughable',
      'lazy',
      'leery',
      'left-out',
      'let-down',
      'lethargic',
      'lied-to',
      'lifeless',
      'limited',
      'listless',
      'lonely',
      'longing',
      'lost',
      'loud',
      'lousy',
      'loveless',
      'low',
      'lowly',
      'ludicrous',
      'lugubrious',
      'lukewarm',
      'lurid',
      'lurking',
      'lying',
      'mad',
      'maladjusted',
      'malcontent',
      'malevolent',
      'malicious',
      'malignant',
      'maniacal',
      'martyred',
      'massacred',
      'mean',
      'measly',
      'melancholy',
      'melodramatic',
      'menacing',
      'mendacious',
      'merciless',
      'messy',
      'miffed',
      'miserable',
      'misguided',
      'mistaken',
      'misunderstood',
      'moaning',
      'mocked',
      'mocking',
      'moderate',
      'monster',
      'monstrous',
      'moody',
      'morbid',
      'mortified',
      'motionless',
      'mournful',
      'muddled',
      'muffled',
      'mundane',
      'murdered',
      'murky',
      'mushy',
      'muted',
      'mysterious',
      'naive',
      'narrow',
      'nasty',
      'nauseated',
      'nebulous',
      'needless',
      'needy',
      'negative',
      'neglected',
      'nerve-racking',
      'nervous',
      'neurotic',
      'nightmarish',
      'nihilistic',
      'noisy',
      'nonchalant',
      'nonplussed',
      'nonsensical',
      'notorious',
      'numb',
      'obdurate',
      'oblivious',
      'obnoxious',
      'obsessed',
      'obstructed',
      'obtuse',
      'odd',
      'offensive',
      'off-kilter',
      'ominous',
      'on-edge',
      'opaque',
      'oppressed',
      'oppressive',
      'ornery',
      'out-of-control',
      'out-of-place',
      'out-of-sorts',
      'out-of-touch',
      'outdone',
      'outraged',
      'over-assertive',
      'overbearing',
      'overcome',
      'overcommitted',
      'overconfident',
      'overcritical',
      'overemotional',
      'overextended',
      'overloaded',
      'overlooked',
      'overpowered',
      'oversensitive',
      'overtaxed',
      'overwhelmed',
      'overworked',
      'overzealous',
      'painful',
      'painstaking',
      'panicked',
      'paralyzed',
      'paranoid',
      'passive',
      'pathetic',
      'patronized',
      'paused',
      'peculiar',
      'peevish',
      'pensive',
      'perfidious',
      'perfunctory',
      'perilous',
      'perplexed',
      'persecuted',
      'perturbed',
      'pessimistic',
      'petrified',
      'petulant',
      'phony',
      'picky',
      'pained',
      'pierced',
      'pissed',
      'pity',
      'pitiful',
      'plagued',
      'plain',
      'plaintive',
      'played',
      'pleading',
      'poisoned',
      'poor',
      'powerless',
      'prattling',
      'precarious',
      'predatory',
      'preoccupied',
      'pressured',
      'preyed-upon',
      'problematic',
      'procrastinating',
      'profound',
      'prohibitive',
      'prolonged',
      'promiscuous',
      'pronounced',
      'prosaic',
      'prostrated',
      'provoked',
      'prudish',
      'pummeled',
      'punished',
      'punitive',
      'puzzled',
      'quaking',
      'quarrelsome',
      'queasy',
      'questioned',
      'quibbling',
      'quiet',
      'quivering',
      'rabid',
      'racist',
      'racked',
      'raided',
      'rambling',
      'rampant',
      'rancorous',
      'ranted',
      'raped',
      'rash',
      'ratting',
      'rattled',
      'ravenous',
      'rebelled',
      'rebuffed',
      'reclusive',
      'recoiling',
      'reconciled',
      'reconsidered',
      'recounted',
      'reeling',
      'refused',
      'regretful',
      'rejected',
      'reminiscent',
      'remorseful',
      'renounced',
      'repressed',
      'repugnant',
      'repulsive',
      'resentful',
      'restless',
      'retaliated',
      'retarded',
      'reticent',
      'retracted',
      'revengeful',
      'reviled',
      'revolted',
      'ridiculous',
      'rigid',
      'riled',
      'rip-roaring',
      'risen',
      'risky',
      'robbed',
      'rocked',
      'rotten',
      'rough',
      'roughed-up',
      'routed',
      'rowdy',
      'ruined',
      'rushed',
      'rusty',
      'ruthless',
      'sabotaged',
      'sacrificed',
      'sad',
      'saddened',
      'sapped',
      'sarcastic',
      'sardonic',
      'sassy',
      'savaged',
      'scared',
      'scarred',
      'scathing',
      'scheming',
      'schizophrenic',
      'scolded',
      'scorned',
      'scraping',
      'screwed-up',
      'screwy',
      'scruffy',
      'scuttled',
      'secluded',
      'second-class',
      'second-rate',
      'secretive',
      'seduced',
      'self-conscious',
      'self-hating',
      'self-indulgent',
      'selfish',
      'self-pitying',
      'self-righteous',
      'self-serving',
      'selfish',
      'sensationalized',
      'sensitive',
      'sentimental',
      'separated',
      'serene',
      'serious',
      'servile',
      'severe',
      'shabby',
      'shadowed',
      'shaken',
      'shaky',
      'shallow',
      'shamed',
      'shameful',
      'shameless',
      'shattered',
      'shifty',
      'shocked',
      'shoddy',
      'short-changed',
      'short-sighted',
      'shouted',
      'shoved',
      'shunned',
      'shut-out',
      'sick',
      'sickened',
      'side-lined',
      'silent',
      'silly',
      'sinned-against',
      'sinister',
      'skeptical',
      'skewed',
      'skittish',
      'slandered',
      'slapped',
      'sleazy',
      'sleep-deprived',
      'sleepless',
      'sloppy',
      'slow',
      'sluggish',
      'slumped',
      'sly',
      'smashed',
      'smothered',
      'snappy',
      'snarled',
      'sneaky',
      'snubbed',
      'sober',
      'solemn',
      'nagging',
      'nauseating',
      'needy',
      'negative',
      'neglected',
      'nerve-wracking',
      'nervous',
      'neurotic',
      'nightmarish',
      'noisy',
      'nonexistent',
      'nonresponsive',
      'nonsensical',
      'notorious',
      'noxious',
      'numb',
      'nutty',
      "not user-friendly",
      "not convenient",
      'not efficient',
      'not effective',
      'not reliable',
      'not secure enough',
      'not trustworthy',
      'not transparent',
      'not organized',
      'not intuitive',
      "not easy to navigate",
      "not easy to understand",
      "not helpful",
      "not responsive",
      "not accommodating",
      "not flexible",
      'Not personalized',
      'Not informative',
      'Not up-to-date',
      'Not innovative',
      'Not competitive',
      'Not value for money',
      'Not satisfactory',
      'Not meeting my expectations',
      'Not worth the effort',
      'Not worth the time',
      'Not enjoyable to use',
      'Not well-designed',
      'Not visually appealing',
      'Not error-free',
      'Not fast enough',
      'Not accessible enough',
      'Not offering enough features',
      'Not providing enough support',
      'Not respecting my privacy',
      'Not respecting my preferences',
      'Not respecting my needs'
          'confusing',
      'never',
      'cant',
      "doesn't",
      'doesnt',
      "doesn't provide",
      'frequent',
      'annoying',
      'is not',
      'not accessible',
      'disabilities',
      'isnot',
      "isn't",
      "wasn't",
      'wasnot',

      'معقد',
      'غير مريح',
      'غير كافٍ',
      'غير مفيد',
      'غير موثوق',
      'غير متاح',
      'غير مرتب',
      'معطل',
      'غير فعال',
      'غير موثوق به',
      'غير متوافق',
      'غير مفهوم',
      'غير دقيق',
      'غير متين',
      'غير مرن',
      'غير مؤمن',
      'غير مجاني',
      'غير مناسب',
      'غير ملائم',
      'غير آمن',
      'غير موثوق فيه',
      'غير متوفر',
      'غير محدث',
      'غير مريح للمستخدم',
      'غير متوافق مع الجوال',
      'غير متوافق مع الحواسيب',
      'غير مريح للعملاء',
      'غير مريح للتنقل',
      'غير مفيد للعملاء',
      'غير متوافق مع الأنظمة الدولية',
      'غير متوافق مع شروط الأمان',
      'غير متوافق مع جميع الأجهزة',
      'غير مرتب وغير منظم',
      'غير مرن في التعامل',
      'غير متوافق مع جميع المتصفحات',
      'غير متوافق مع أنظمة التشغيل',
      'غير متاح على مدار الساعة',
      'غير متوافق مع الخدمات المصرفية الأخرى',
      'غير سلس في التعامل',
      'غير متوافق مع جميع اللغات',
      'غير متوافق مع الأجهزة القديمة',
      'غير متوافق مع العملاء ذوي الاحتياجات الخاصة',
      'غير مريح للتحويلات الدولية',
      'غير مفيد للشركات والمؤسسات المالية',
      'غير متوافق مع شروط الخصوصية',
      'غير مريح في متابعة الحسابات',
      'غير متوافق مع العملاء الجدد',
      'غير متوافق مع الأعمال المصرفية الكبيرة',
      'غير متوافق مع الأعمال المصرفية الصغيرة',
      'غير فاعل في تقديم الخدمات المصرفية',
      'غير متوافق مع أنواع الحسابات المختلفة',
      'غير متوافق مع الأنظمة الأمنية المطلوبة',
      'غير متوافق مع جميع الشبكات',
      'غير فعال في توفير الخدمات المصرفية عن بعد',
      'غير مريح لإدارة الحسابات المصرفية',
      'غير متوافق مع جميع البلدان',
      'غير متوافق مع العملاء ذوي الخبرة',
      'غير متوافق مع الأعمال المصرفية الدولية',
      'غير متوافق مع أنواع العملات المختلفة',
      'غير متوافق مع طرق الدفع المفضلة',
      'غير متوافق مع العملاء الشباب',
      'غير مريح للتسجيل والدخول',
      'غير مفيد للعملاء العاديين',
      'غير مريح للعملاء الذين لديهم عدة حسابات',
      'غير متوافق مع العملاء الذين يريدون السفر',
      'غير متوافق مع أنظمة الشركات',
      'غير متوافق مع الأساليب المفضلة للعملاء',
      'غير متوافق مع العملاء الذين يريدون الاستثمار',
      'غير متوافق مع العملاء الذين يريدون التوفير',
      'غير متوافق مع العملاء الذين يريدون الإقراض',
      'غير متوافق مع العملاء الذين يريدون الودائع',
      'غير مريح للعملاء الذين يريدون المتابعة الشهرية',
      'غير مفيد للعملاء الذين يريدون الإحصائيات',
      'غير مريح للعملاء الذين يريدون التقارير المالية',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية الشخصية',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية العقارية',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية للشركات',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية للمؤسسات',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية للمستثمرين',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية للتجار',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية للشراء عبر الإنترنت',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية للتحويلات الدولية',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية للتأمين',
      'غير متوافق مع العملاء الذين يريدون الخدمات المصرفية للتمويل'
          'غير مناسبة للعملاء',
      'غير متوافقة مع الجوالات',
      'غير متوافقة مع الحواسيب المحمولة',
      'غير مريحة للعملاء',
      'غير مريحة للتنقل',
      'غير مفيدة للعملاء',
      'غير متوافقة مع الأنظمة الدولية',
      'غير متوافقة مع شروط الأمان',
      'غير متوافقة مع جميع الأجهزة',
      'غير مرتبة وغير منظمة',
      'غير مرنة في التعامل',
      'غير متوافقة مع جميع المتصفحات',
      'غير متوافقة مع أنظمة التشغيل',
      'غير متاحة على مدار الساعة',
      'غير متوافقة مع الخدمات المصرفية الأخرى',
      'غير سلسة في التعامل',
      'غير متوافقة مع جميع اللغات',
      'غير متوافقة مع الأجهزة القديمة',
      'غير متوافقة مع العملاء ذوي الاحتياجات الخاصة',
      'غير مريحة للتحويلات الدولية',
      'غير مفيدة للشركات والمؤسسات المالية',
      'غير متوافقة مع شروط الخصوصية',
      'غير مريحة في متابعة الحسابات',
      'غير متوافقة مع العملاء الجدد',
      'غير متوافقة مع الأعمال المصرفية الكبيرة',
      'غير متوافقة مع الأعمال المصرفية الصغيرة',
      'غير فاعلة في تقديم الخدمات المصرفية',
      'غير متوافقة مع أنواع الحسابات المختلفة',
      'غير متوافقة مع الأنظمة الأمنية المطلوبة',
      'غير متوافقة مع جميع الشبكات',
      'غير فعالة في توفير الخدمات المصرفية عن بعد',
      'غير مريحة لإدارة الحسابات المصرفية',
      'غير متوافقة مع جميع البلدان',
      'غير متوافقة مع العملاء ذوي الخبرة',
      'غير متوافقة مع الأعمال المصرفية الدولية',
      'غير متوافقة مع أنواع العملات المختلفة',
      'غير متوافقة مع طرق الدفع المفضلة',
      'غير متوافقة مع العملاء الشباب',
      'غير مريحة للتسجيل والدخول',
      'غير مفيدة للعملاء العاديين',
      'غير مريحة للعملاء الذين لديهم عدة حسابات',
      'غير متوافقة مع العملاء الذين يريدون السفر',
      'غير متوافقة مع أنواعدة الأجهزة الذكية',
      'غير متوافقة مع العملاء ذوي الأسلوب الشخصي المختلف',
      'غير متوافقة مع العملاء ذوي الاحتياجات الخاصة',
      'غير متوافقة مع العملاء الذين يستخدمون برامج مساعدة لتصفح الإنترنت',
      'غير متوافقة مع العملاء الذين يستخدمون متصفحات الويب الغير شائعة',
      'غير مريحة للعملاء الذين يريدون التحكم في إعدادات الخصوصية',
      'غير مريحة للعملاء الذين يريدون إجراء عمليات مصرفية متعددة في نفس الوقت',
      'غير متوافقة مع العملاء الذين يفضلون التعامل باللغة الإنجليزية',
      'غير متوافقة مع العملاء الذين يفضلون التعامل باللغات الأخرى',
      'غير متوافقة مع العملاء الذين يريدون الوصول إلى الخدمات المصرفية دون اتصال بالإنترنت',
      'غير متوافقة مع العملاء الذين يريدون إدارة حساباتهم المصرفية بشكل مستقل',
      'غير متوافقة مع العملاء الذين يريدون الوصول إلى الخدمات المصرفية عبر الهاتف فقط',
      'غير متوافقة مع العملاء الذين يريدون الوصول إلى الخدمات المصرفية عبر البريد الإلكتروني فقط',
      'غير متوافقة مع العملاء الذين يريدون الوصول إلى الخدمات المصرفية عبر الرسائل النصية القصيرة فقط',
      'غير متوافقة مع العملاء الذين يريدون الوصول إلى الخدمات المصرفية عبر تطبيقات الهواتف الذكية فقط',
      'غير متوافقة مع العملاء الذين يريدون الوصول إلى الخدمات المصرفية عبر تطبيقات الحواسيب الشخصية فقط',
      'غير متوافقة مع العملاء الذين يريدون الوصول إلى الخدمات المصرفية عبر تطبيقات الأجهزة اللوحية فقط',
      'غير متوافقة مع العملاء الذين لا يريدون تحميل أي تطبيقات للوصول إلى الخدمات المصرفية',
      'غير متوافقة مع العملاء الذين يريدون نظاماً سهل الاستخدام والتنقل بين الصفحات',
      'غير متوافقة مع العملاء الذين يفضلون الدفع النقدي عند إجراء العمليات المصرفية'

    ];

    int positiveCount = 0;
    int negativeCount = 0;

    feedback = preprocessFeedback(feedback);
    List<String> arabicSentences = splitSentences(feedback);

    // Check Arabic keywords in each sentence
    for (String sentence in arabicSentences) {
      List<String> arabicTokens = sentence.split(' ');
      for (String token in arabicTokens) {
        if (positiveKeywords.contains(token)) {
          positiveCount++;
        }
        if (negativeKeywords.contains(token)) {
          negativeCount++;
        }}}

        // English words

        List<String> tokens = feedback.split(' ');
        for (String token in tokens) {
          if (positiveKeywords.contains(token)) {
            positiveCount++;
          }
          if (negativeKeywords.contains(token)) {
            negativeCount++;
          }
        }
        if (positiveCount > negativeCount) {
          return 'Positive';
        } else if (negativeCount > positiveCount) {
          return 'Negative';
        } else {
          return 'Neutral';
        }
      }

      // Define a function to extract the most common themes from the feedback
      List<String> extractThemes() {
        List<String> themes = [];
        for (dynamic feedback in feedbackList) {
          String processedFeedback = preprocessFeedback(feedback['complement']);
          // Define a list of keywords to look for in the feedback
          List<String> keywords = [
            'convenient',
            'user-friendly',
            'time-saving',
            'secure',
            'efficient'
          ];
          for (String keyword in keywords) {
            if (processedFeedback.contains(keyword)) {
              themes.add(keyword);
            }
          }
        }

        // Count the frequency of each theme and return the top 5 themes
        Map<String, int> themeCounts = {};
        for (String theme in themes) {
          if (themeCounts.containsKey(theme)) {
            themeCounts[theme] = (themeCounts[theme] ?? 0) + 1;
          } else {
            themeCounts[theme] = 1;
          }
        }
        List<MapEntry<String, int>> sortedThemeCounts =
        themeCounts.entries.toList();
        sortedThemeCounts.sort((a, b) => b.value.compareTo(a.value));
        List<String> topThemes = [];
        for (int i = 0; i < 50 && i < sortedThemeCounts.length; i++) {
          topThemes.add(sortedThemeCounts[i].key);
        }
        return topThemes;
      }
      Map<String, int> extractSentimentCounts() {
        int positiveCount = 0;
        int negativeCount = 0;
        int neutralCount = 0;
        for (dynamic feedback in feedbackList) {
          String sentiment = analyzeSentiment(feedback['complement']);

          if (sentiment == 'Positive') {
            positiveCount++;
          } else if (sentiment == 'Negative') {
            negativeCount++;
          } else {
            neutralCount++;
          }
        }
        return {
          'Positive': positiveCount,
          'Negative': negativeCount,
          'Neutral': neutralCount
        };
      }


      @override
      Widget build(BuildContext context) {
        return MaterialApp(
            debugShowCheckedModeBanner: false,
            home: DefaultTabController(
                length: 1,
                child: Scaffold(
                    appBar: AppBar(
                      toolbarHeight: 70,
                      flexibleSpace: Padding(
                        padding: const EdgeInsets.fromLTRB(10, 0, 0, 0),
                        child: Container(
                            child: Row(children: [
                              Image(
                                image: AssetImage("images/logo3.jpeg"),
                                height: 150,
                              ),
                              SizedBox(width: 1300),
                              IconButton(
                                  onPressed: () {
                                    Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                          builder: (context) =>
                                              Search(
                                                  Email: Email,
                                                  Password: Password,
                                                  username: username,
                                                  mobile: mobile,
                                                  Gender: Gender,
                                                  dob: dob,
                                                  id: id,
                                                  Adress: Adress,
                                                  nationalid: nationalid),
                                        ));
                                  },
                                  icon: Icon(
                                    Icons.person_search_rounded,
                                    color: Colors.white,
                                    size: 30,
                                  )),
                              SizedBox(
                                width: 10,
                              ),
                            ])),
                      ),
                      backgroundColor: Color(0xff8d0000),
                    ),
                    body: ListView(children: [
                      TabBar(
                        unselectedLabelColor: Color(0xff8d0000),
                        indicator: BoxDecoration(
                            border: Border(
                              bottom: BorderSide(
                                width: 5.0,
                                color: Color(0xff8d0000),
                              ),
                            )),
                        labelColor: Color(0xff8d0000),
                        labelPadding: EdgeInsets.only(right: 0, left: 0),
                        tabs: [
                          PlutoMenuBarDemo(
                              Email: Email,
                              Password: Password,
                              username: username,
                              mobile: mobile,
                              Gender: Gender,
                              dob: dob,
                              id: id,
                              Adress: Adress,
                              nationalid: nationalid),
                        ],
                      ),
                      Column(children: [
                        SizedBox(
                          height: 10,
                        ),
                        Center(
                          child: Text(" Customer feedback analysis ",
                              style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 30,
                                  fontWeight: FontWeight.bold)),
                        ),
                        Container(
                          padding: EdgeInsets.all(16.0),
                          color: Colors.grey[300],
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                            children: [
                              Column(
                                children: [
                                  Text(
                                    'Positive',
                                    style: TextStyle(
                                      color: Colors.green,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                  Text(
                                    '${(extractSentimentCounts()['Positive']! /
                                        feedbackList.length * 100)
                                        .toStringAsFixed(1)}%',
                                  ),
                                ],
                              ),
                              Column(
                                children: [
                                  Text(
                                    'Negative',
                                    style: TextStyle(
                                      color: Colors.red,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                  Text(
                                    '${(extractSentimentCounts()['Negative']! /
                                        feedbackList.length * 100)
                                        .toStringAsFixed(1)}%',
                                  ),
                                ],
                              ),
                              Column(
                                children: [
                                  Text(
                                    'Neutral',
                                    style: TextStyle(
                                      color: Colors.yellow,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                  Text(
                                    '${(extractSentimentCounts()['Neutral']! /
                                        feedbackList.length * 100)
                                        .toStringAsFixed(1)}%',
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                        SizedBox(
                          height: 650,
                          child: feedbackList.isEmpty
                              ? Center(child: CircularProgressIndicator())
                              : ListView.builder(
                            itemCount: feedbackList.length,
                            itemBuilder: (context, index) {
                              String feedback =
                              feedbackList[index]['complement'];
                              String sentiment = analyzeSentiment(feedback);
                              List<String> themes = extractThemes();

                              Color color;

                              if (sentiment == 'Positive') {
                                color = Colors.green;
                              } else if (sentiment == 'Negative') {
                                color = Colors.red;
                              } else {
                                color = Colors.yellow;
                              }

                              return Padding(
                                padding: const EdgeInsets.all(8.0),
                                child: Card(
                                  child: Padding(
                                    padding: const EdgeInsets.all(16.0),
                                    child: Column(
                                      crossAxisAlignment:
                                      CrossAxisAlignment.start,
                                      children: [
                                        Text(
                                          'Message: $feedback',
                                          style: TextStyle(
                                            fontWeight: FontWeight.bold,
                                          ),
                                        ),
                                        SizedBox(height: 8),
                                        Text(
                                            'Date: ${feedbackList[index]['Date']}'),
                                        SizedBox(height: 8),
                                        Text(
                                            'Time: ${feedbackList[index]['Time']}'),
                                        SizedBox(height: 8),
                                        Text(
                                            'Account number: ${feedbackList[index]['accountnumber']}'),
                                        SizedBox(height: 8),
                                        Text(
                                            'Mobile: ${feedbackList[index]['mobile']}'),
                                        SizedBox(height: 16),
                                        Row(
                                          mainAxisAlignment:
                                          MainAxisAlignment.spaceBetween,
                                          children: [
                                            Text(
                                              '$sentiment',
                                              style: TextStyle(
                                                fontStyle: FontStyle.italic,
                                                color: color,
                                                fontSize: 18,
                                                fontWeight: FontWeight.bold,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              );
                            },
                          ),
                        )
                      ])
                    ])
                )));
      }
    }